added setInsecure for esp32
khoih-prog/WebSockets2_Generic pull request #18
Opened 2021-05-04 15:12 UTC by apwwn

I've added the setInsecure fonction to be able to work with self signed certificate, it's really usefull in dev ;)

Usage example in Secured ESP32 Websockets Client:
replace client.setCACert(echo_org_ssl_ca_cert); by client.setInsecure(); and voila, it's working

2021-05-04 18:33 UTC, khoih-prog commented
Hi 

Thanks for your PR. I prefer you change the PR as follows to not using an extra variable `_use_insecure` (similar to ESP8266 solution) and setInsecure is only optional whenever we don't need, don't have or don't use CA Certs

1. client.hpp: no change  by deleting

```
bool _use_insecure;
```

2. WebSockets2_Generic_Client.hpp

Don't need this:

```
this->_use_insecure = true;
```

and change to

```
if ( this->_optional_ssl_ca_cert || this->_optional_ssl_client_ca || this->_optional_ssl_private_key )
{
  if (this->_optional_ssl_ca_cert)
  {
    client->setCACert(this->_optional_ssl_ca_cert);
  }

  if (this->_optional_ssl_client_ca)
  {
    client->setCertificate(this->_optional_ssl_client_ca);
  }

  if (this->_optional_ssl_private_key)
  {
    client->setPrivateKey(this->_optional_ssl_private_key);
  }
}  
else
{
  client->setInsecure();
}
```

3. esp32_tcp.hpp : OK with your change
---

Usage:

Just keep these CA Certs as `nullptr`, and the `client->setInsecure()` will be called automatically

```
const char* _optional_ssl_ca_cert = nullptr;
const char* _optional_ssl_client_ca = nullptr;
const char* _optional_ssl_private_key = nullptr;
```

2021-05-04 23:40 UTC, khoih-prog requested changes
Please change according to reply.
I'll add 2 more examples to demonstrate the new feature.

2021-05-05 14:27 UTC, khoih-prog approved these changes

2021-05-05 14:27 UTC, merged

2021-05-05 14:29 UTC, khoih-prog commented
Thanks Lionel,

The PR has been merged and I'll add some more mods before publishing a new Release.

Regards,

2021-05-05 14:41 UTC, khoih-prog commented
Hi Lionel,

Just added 2 new InSecure-mode examples. Please retest to be sure everything is OK. Thanks.

1. [InSecured-Esp32-Client](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/ESP32/InSecured-Esp32-Client)
2. [InSecured-Esp8266-Client](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/ESP8266/InSecured-Esp8266-Client)

2021-05-05 15:17 UTC, apwwn commented
I have tested the example with an ESP32-PICO-KIT (esp32-pico-d4) and an ESP32-S2 SAOLA, it's working for the 2 boards ;)

2021-05-05 15:41 UTC, khoih-prog commented
Thanks. I'll published new release soon.

2021-05-05 17:36 UTC, khoih-prog commented
HI Lionel,

Just published the new [**WebSockets2_Generic** releases v1.2.4](https://github.com/khoih-prog/WebSockets2_Generic/releases/tag/v1.2.4) with a note about your contribution in [**Contributions and Thanks**](https://github.com/khoih-prog/WebSockets2_Generic#contributions-and-thanks).

Hoping to get more from you.

Regards,

---

### Release v1.2.4

1. Add InSecure mode for ESP32. For more info, check [**Add setInsecure for esp32** #18](https://github.com/khoih-prog/WebSockets2_Generic/pull/18)
2. Add InSecude-mode examples for ESP32/ESP8266

2021-05-20 11:06 UTC, emanavas commented
I update from Arduino ide to Release v1.2.4 and produce a error 
D:\DC100\FW\arduino-1.8.13\portable\sketchbook\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/network/esp32/esp32_tcp.hpp:71:24: error: 'class WiFiClientSecure' has no member named 'setInsecure'
           this->client.setInsecure();

2021-05-20 15:33 UTC, khoih-prog commented
@emanavas 

You have to install ESP32 core, at least the version v1.0.5.
The `setInsecure()` has been defined in [**WiFiClientSecure**.h#L66](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/WiFiClientSecure.h#L66)

Next time, it's better to create a new issue, not post in the closed PR like this.